record:
  fields:
    entity_id:
      example: "media_player.tv_box_livingroom"

rewind:
  fields:
    entity_id:
      example: "media_player.tv_box_livingroom"

fast_forward:
  fields:
    entity_id:
      example: "media_player.tv_box_livingroom"

remote_key_press:
  fields:
    entity_id:
      example: "media_player.tv_box_livingroom"
    remote_key:
      example: TV
